export const PlayerActionTypes = {
  CURRENT_PLAYER: 'CURRENT_PLAYER',
  EDIT_PLAYER_NAME: 'EDIT_PLAYER_NAME',
  PLAYER_POWER: 'PLAYER_POWER',
  PLAYER_AGIBILITY: 'PLAYER_AGIBILITY',
  PLAYER_INTELLECT: 'PLAYER_INTELLECT',
  PLAYER_CHARISMA: 'PLAYER_CHARISMA',
  PLAYER_ATTACK: 'PLAYER_ATTACK',
  PLAYER_STELS: 'PLAYER_STELS',
  PLAYER_ATTACH_ARCH: 'PLAYER_ATTACH_ARCH',
  PLAYER_EDUCABILITY: 'PLAYER_EDUCABILITY',
  PLAYER_SURVIVAL: 'PLAYER_SURVIVAL',
  PLAYER_MEDICINE: 'PLAYER_MEDICINE',
  PLAYER_FEAR: 'PLAYER_FEAR',
  PLAYER_INSIGHT: 'PLAYER_INSIGHT',
  PLAYER_APPEARANCE: 'PLAYER_APPEARANCE',
  PLAYER_MANIPULATION: 'PLAYER_MANIPULATION',
  REGISTER_PALYER: "REGISTER_PALYER",
}

// export const PlayerNameEdit = {
    
//   }